CREATE FUNCTION [StringToBase64] (@string VARCHAR(MAX))
RETURNS VARCHAR(MAX) AS 
BEGIN 
  DECLARE @xml = (SELECT CAST(@string VARBINARY(MAX)) FOR XML PATH(''), BINARY BASE64)
  RETURN @xml.value('.', 'VARCHAR(MAX)')
END;